# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='student_id',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
