# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_checkin_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('lastcheckintime', models.DateField(default=django.utils.timezone.now)),
                ('checkintimes', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checkin',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='checkin.Student'),
        ),
    ]
